In [4]:
import torch
from torch.utils.data import Dataset, DataLoader

class SimpleDataset(Dataset) :
    def __init__(self, t):
        self.t = t
        
    def __len__(self) :
        return self.t

    def __getitem__(self, idx) :
        return torch.LongTensor([idx])

if __name__ == "__main__":
    dataset = SimpleDataset(t=5)
    print(len(dataset))
    it = iter(dataset)
    
    for i in range(10):
        print(i, next(it))

5
0 tensor([0])
1 tensor([1])
2 tensor([2])
3 tensor([3])
4 tensor([4])
5 tensor([5])
6 tensor([6])
7 tensor([7])
8 tensor([8])
9 tensor([9])


In [ ]:
if __name__ == "__main__":
    dataset = SimpleDataset(t=5)
    dataloader = DataLoader(dataset = dataset, 
                           batch_size =2 ,
                           shuffle = True,
                           drop_last = False)

    for epoch in range(2):
        print(f"epoch: {epoch}")
        for batch in dataloader :
            print(batch)

epoch: 0
tensor([[3],
        [1]])
tensor([[4],
        [2]])
tensor([[0]])
epoch: 1
tensor([[1],
        [4]])
tensor([[0],
        [2]])
tensor([[3]])
